package com.matkansuunnittelija.errormanager;

/**
 * Tilakoodi joka helpottaa eri viestien käsittelyä.
 * Käyttöliittymä voi helposti vastata tilakoodeeihin, joita muut komponentit palauttavat.
 * @author Samuli
 */
public enum StatusCode {

    STATUS_TRAVEL_PLAN_CREATE_FAIL_ALREADY_EXISTS,
    STATUS_TRAVEL_PLAN_CREATE_FAIL_FILE_NOT_FOUND,
    STATUS_TRAVEL_PLAN_CREATE_SUCCEED,
    STATUS_TRAVEL_PLAN_CREATE_FAIL_DATE_DIFFERENCE_TOO_LONG,
    STATUS_TRAVEL_PLAN_CREATE_FAIL_START_DATE_AFTER_END_DATE,
    STATUS_TRAVEL_PLAN_INFO_OK,
    STATUS_TRAVREL_PLAN_CREATE_FAIL_DATE_WRONG_FORMAT,
    STATUS_TRAVEL_PLAN_ADD_EVENT_TIME_FORMAT_WRONG_FORMAT,
    STATUS_TRAVEL_PLAN_ADD_EVENT_TIME_ALREADY_EXISTS,
    STATUS_TRAVEL_PLAN_ADD_EVENT_SUCCEED,
    STATUS_TRAVEL_PLAN_REMOVE_EVENT_SUCCEED,
    STATUS_TRAVEL_PLAN_ADD_EVENT_ILLEGAL_CHARACTER
}
