package com.matkansuunnittelija.userinterface;

import com.matkansuunnittelija.StatusCode;
import com.matkansuunnittelija.controllers.TravelPlanController;
import com.matkansuunnittelija.errormanager.ErrorManager;
import javax.swing.JOptionPane;

/**
 * Käyttöliittymäikkuna uuden matkasuunnitelman lisäämiseen
 * @author Samuli
 */
public class AddNewTravelPlanGUI extends javax.swing.JDialog {

    private TravelPlanController travelPlanController;
    private MatkansuunnittelijaGUI parent;

    /**
     * Creates new form AddNewTravelPlanGUI
     *
     * @param parent
     */
    public AddNewTravelPlanGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = (MatkansuunnittelijaGUI) parent;
        travelPlanController = TravelPlanController.getInstance();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        travelPlanNameLabel = new javax.swing.JLabel();
        travelPlanNameField = new javax.swing.JTextField();
        travelPlanStartDateField = new javax.swing.JTextField();
        createNewTravelPlanButton = new javax.swing.JButton();
        travelPlanEndDateField = new javax.swing.JTextField();
        infoLabel = new javax.swing.JLabel();
        travelPlanStartDateLabel = new javax.swing.JLabel();
        travelPlanEndDateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Uusi matkasuunnitelma");

        travelPlanNameLabel.setText("Matkasuunnitelman nimi:");

        createNewTravelPlanButton.setText("Luo uusi matkasuunnitelma");
        createNewTravelPlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewTravelPlanButtonActionPerformed(evt);
            }
        });

        infoLabel.setForeground(new java.awt.Color(51, 51, 0));
        infoLabel.setText("Päivämäärän tulee olla muotoa dd.mm.yyyy(esim. 10.11.2012)");

        travelPlanStartDateLabel.setText("Matkan alkamispäivämäärä:");

        travelPlanEndDateLabel.setText("Matkan päättymispäivämäärä:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(infoLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(travelPlanNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(travelPlanNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(createNewTravelPlanButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(travelPlanStartDateLabel)
                                    .addComponent(travelPlanEndDateLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(travelPlanEndDateField, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                                    .addComponent(travelPlanStartDateField))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(travelPlanNameLabel)
                    .addComponent(travelPlanNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(travelPlanStartDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(travelPlanStartDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(travelPlanEndDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(travelPlanEndDateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel)
                .addGap(27, 27, 27)
                .addComponent(createNewTravelPlanButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createNewTravelPlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewTravelPlanButtonActionPerformed

        StatusCode code = travelPlanController.createNewTravelPlan(travelPlanNameField.getText(), travelPlanStartDateField.getText(), travelPlanEndDateField.getText());
        switch (code) {
            case STATUS_TRAVEL_PLAN_CREATE_SUCCEED:
                this.setVisible(false);
                this.dispose();
                this.parent.addTravelPlanToMenu(travelPlanNameField.getText());
                this.parent.openEditTravelPlanMenu(travelPlanNameField.getText());
                break;        
            default:
                JOptionPane.showMessageDialog(null, ErrorManager.getStringForErrorCode(code));
                break;
        }
    }//GEN-LAST:event_createNewTravelPlanButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createNewTravelPlanButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JTextField travelPlanEndDateField;
    private javax.swing.JLabel travelPlanEndDateLabel;
    private javax.swing.JTextField travelPlanNameField;
    private javax.swing.JLabel travelPlanNameLabel;
    private javax.swing.JTextField travelPlanStartDateField;
    private javax.swing.JLabel travelPlanStartDateLabel;
    // End of variables declaration//GEN-END:variables
}
