package com.matkansuunnittelija.userinterface;

import com.matkansuunnittelija.errormanager.StatusCode;
import com.matkansuunnittelija.controllers.TravelPlanController;
import com.matkansuunnittelija.errormanager.ErrorManager;
import com.matkansuunnittelija.travelplanobjects.TravelPlan;
import javax.swing.JOptionPane;

/**
 * Käyttöliittymäikkuna uuden aktiviteetin lisäämiseen
 *
 * @author Samuli
 */
public class AddNewActivityGUI extends javax.swing.JDialog {

    private final TravelPlan plan;
    private final String dayPlanName;
    private final TravelPlanController travelPlanController;
    private final EditDayActivitiesGUI parent;


    public AddNewActivityGUI(EditDayActivitiesGUI parent, boolean modal, TravelPlan plan, String dayPlanName) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.plan = plan;
        this.dayPlanName = dayPlanName;
        this.travelPlanController = TravelPlanController.getInstance();
    }

    private void addNewActivity() {
        StatusCode code = travelPlanController.addDayEventToDayPlan(plan.getName(), dayPlanName, activityNameField.getText(), activityTimeField.getText(), activityDescriptionTextArea.getText());
        switch (code) {
            case STATUS_TRAVEL_PLAN_ADD_EVENT_SUCCEED:
                this.setVisible(false);
                this.dispose();
                this.parent.addActivityToTheList(activityNameField.getText(), activityTimeField.getText());
                break;

            default:
                JOptionPane.showMessageDialog(null, ErrorManager.getStringForErrorCode(code));
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activityNameLabel = new javax.swing.JLabel();
        activityNameField = new javax.swing.JTextField();
        activityTimeLabel = new javax.swing.JLabel();
        activityTimeField = new javax.swing.JTextField();
        activityDescriptionLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        activityDescriptionTextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        infoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lisää uusi aktiviteetti");

        activityNameLabel.setText("Aktiviteetin nimi:");

        activityTimeLabel.setText("Aktiviteetin aika:");

        activityDescriptionLabel.setText("Aktiviteetin kuvaus:");

        activityDescriptionTextArea.setColumns(20);
        activityDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(activityDescriptionTextArea);

        jButton1.setText("Lisää aktiviteetti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        infoLabel.setText("Huom: tulee olla muotoa HH:mm(esim 23:21)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(activityDescriptionLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(activityNameLabel)
                            .addComponent(activityTimeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(infoLabel)
                                .addGap(0, 106, Short.MAX_VALUE))
                            .addComponent(activityTimeField)
                            .addComponent(activityNameField))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activityNameLabel)
                    .addComponent(activityNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activityTimeLabel)
                    .addComponent(activityTimeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activityDescriptionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addNewActivity();
    }//GEN-LAST:event_jButton1ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityDescriptionLabel;
    private javax.swing.JTextArea activityDescriptionTextArea;
    private javax.swing.JTextField activityNameField;
    private javax.swing.JLabel activityNameLabel;
    private javax.swing.JTextField activityTimeField;
    private javax.swing.JLabel activityTimeLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
