package com.matkansuunnittelija.userinterface;

import com.matkansuunnittelija.StatusCode;
import com.matkansuunnittelija.controllers.TravelPlanController;
import com.matkansuunnittelija.travelplanobjects.DayEvent;
import com.matkansuunnittelija.travelplanobjects.TravelPlan;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * Käyttöliittymäikkuna tietyn päivän aktiviteettien muokkaamiseen
 *
 * @author Samuli
 */
public class EditDayActivitiesGUI extends javax.swing.JDialog {

    private final TravelPlanController controller;
    private DefaultListModel listViewModel;
    private final TravelPlan plan;
    private final String dayPlanName;

    private String getListFormattedStringForDayEvent(String name, String time) {
        return name + " - " + time;
    }

    private String getNameFromFormattedStringForDayEvent(String formattedString) {
        return formattedString.split(" - ")[0];
    }

    private void initListViewWithActivities() {
        listViewModel = (DefaultListModel) jList1.getModel();
        listViewModel.removeAllElements();

        for (DayEvent e : plan.getDayPlan(dayPlanName).getDayEvents()) {
            listViewModel.addElement(getListFormattedStringForDayEvent(e.getName(), e.getTime()));
        }
    }

    public void addActivityToTheList(String name, String time) {
        listViewModel.addElement(getListFormattedStringForDayEvent(name, time));
    }

    private void openAddNewActivityMenu() {
        AddNewActivityGUI addNewActivity = new AddNewActivityGUI(this, true, plan, dayPlanName, controller);
        addNewActivity.setVisible(true);
    }

    private String generateTitleForWindow() {
        return plan.getName() + " - " + dayPlanName + " - Aktiviteetit";
    }

    /**
     * Creates new form EditDayActivitiesGUI
     * @param parent
     * @param modal
     * @param plan
     * @param dayPlanName
     */
    public EditDayActivitiesGUI(javax.swing.JDialog parent, boolean modal, TravelPlan plan, String dayPlanName) {
        super(parent, modal);
        initComponents();
        this.plan = plan;
        this.dayPlanName = dayPlanName;
        this.setTitle(generateTitleForWindow());
        MatkansuunnittelijaGUI temp = (MatkansuunnittelijaGUI) parent.getParent();
        this.controller = temp.getTravelPlanController();
        initListViewWithActivities();
    }

    private DayEvent getSelectedEvent() {
        int index = jList1.getSelectedIndex();
        DayEvent event = controller.getTravelPlan(plan.getName()).getDayPlan(dayPlanName).getDayEventWithName(getNameFromFormattedStringForDayEvent((String) listViewModel.getElementAt(index)));
        return event;
    }

    private String getDescriptionForSelectedItem() {
        DayEvent event = getSelectedEvent();
        if (event != null) {
            return event.getDescription();
        }

        return "";
    }

    private String getNameForSelectedItem() {
        DayEvent event = getSelectedEvent();
        if (event != null) {
            return event.getName();
        }

        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jList1.setModel(new DefaultListModel());
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                dayActivitySelected(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Valitun aktiviteetin kuvaus");

        jButton1.setText("Lisää uusi aktiviteetti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Poista valittu aktiviteetti");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Aktiviteetit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        openAddNewActivityMenu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dayActivitySelected(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_dayActivitySelected
        if (jList1.getSelectedIndex() != -1) {
            jTextArea1.setText(getDescriptionForSelectedItem());
        } else {
            jTextArea1.setText(" ");
        }
    }//GEN-LAST:event_dayActivitySelected

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jList1.getSelectedIndex() != -1) {
            StatusCode code = controller.deleteDayEventFromDayPlan(plan.getName(), dayPlanName, getNameForSelectedItem());
            switch (code) {
                case STATUS_TRAVEL_PLAN_REMOVE_EVENT_SUCCEED:
                    int index = jList1.getSelectedIndex();
                    listViewModel.removeElementAt(index);
                    break;
                case STATUS_TRAVEL_PLAN_CREATE_FAIL_FILE_NOT_FOUND:
                    JOptionPane.showMessageDialog(null, "Vakava virhe: Tiedostoa ei löytynyt.");
                    break;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
